name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_USER: rauthy
          POSTGRES_PASSWORD: 123SuperSafe
          POSTGRES_DB: rauthy
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U rauthy"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y just libpq-dev
          cargo install sqlx-cli --no-default-features --features postgres
      
      - name: Ensure Docker network exists
        run: docker network create rauthy-dev || true

      - name: List Docker networks (debugging step)
        run: docker network ls
      
      - name: Fix Cargo registry permissions
        run: |
          mkdir -p /home/runner/.cargo/registry
          sudo chown -R 1001:118 /home/runner/.cargo/registry

      # - name: Build Builder Image
      #   run: just build-builder  # Uses values from Justfile

      # - name: Start PostgreSQL
      #   run: just postgres-start
      
      # - name: Wait for PostgreSQL to be Ready
      #   run: |
      #     echo "Waiting for PostgreSQL to be ready..."
      #     for i in {1..15}; do
      #       if docker exec rauthy-db-postgres pg_isready -U rauthy; then
      #         echo "PostgreSQL is ready!"
      #         exit 0
      #       fi
      #       echo "Still waiting for PostgreSQL..."
      #       sleep 3
      #     done
      #     echo "PostgreSQL did not become ready in time" >&2
      #     exit 1

      # - name: Debug PostgreSQL Status
      #   run: |
      #     echo "PostgreSQL containers:"
      #     docker ps
      #     echo "Checking if PostgreSQL is listening on port 5432..."
      #     netstat -tulnp | grep 5432 || echo "PostgreSQL is not listening!"

      # - name: Debug PostgreSQL Connection
      #   run: |
      #     echo "Checking if PostgreSQL accepts connections..."
      #     PGPASSWORD=123SuperSafe psql -h rauthy-db-postgres -U rauthy -d rauthy -c '\dt' || echo "Failed to connect to PostgreSQL"
      
      - name: Run Migrations
        env:
          DATABASE_URL: postgresql://rauthy:123SuperSafe@localhost:5432/rauthy
        run: just migrate-postgres

      - name: Build Application Image
        env:
          DATABASE_URL: postgresql://rauthy:123SuperSafe@localhost:5432/rauthy
        run: just build