name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: rauthy
          POSTGRES_PASSWORD: 123SuperSafe
          POSTGRES_DB: rauthy
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y just libpq-dev
      
      - name: Ensure Docker network exists
        run: docker network create rauthy-dev || true

      - name: List Docker networks (debugging step)
        run: docker network ls

      - name: Set up environment
        run: echo "DATABASE_URL=postgresql://rauthy:123SuperSafe@localhost:5432/rauthy" >> $GITHUB_ENV
      
      - name: Debug PostgreSQL Connection
        run: |
          echo "Testing DB Connection..."
          PGPASSWORD=123SuperSafe psql -h localhost -U rauthy -d rauthy -c '\dt'

      # - name: Build Builder Image
      #   run: just build-builder  # Uses values from Justfile

      - name: Build Application Image
        run: just build